name: Build and Publish

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

env:
  PUSH: false
  TAGS: wolfsoftwareltd/caretaker:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup conditional variables
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/tags/v}"

          echo PUSH=true >> "${GITHUB_ENV}"
          echo TAGS="wolfsoftwareltd/caretaker:latest,wolfsoftwareltd/caretaker:$RELEASE_VERSION" >> "${GITHUB_ENV}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Login to Github Packages
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: ${{ env.PUSH }}
          tags: ${{ env.TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
